image: "chef/chefdk:3.1.0"

before_script:
  - env
  - chef --version

stages:
  - syntax
  - lint
  - unit
  - integration

syntax:
  stage: syntax
  script:
    - knife cookbook test -o . -a

cookstyle:
  stage: lint
  script:
    - cookstyle

foodcritic:
  stage: lint
  script:
    - foodcritic --exclude test --epic-fail any .

unit:
  stage: unit
  script:
    - rspec --format documentation --color

.integration: &tk
  stage: integration
  before_script:
    - env
    - chef --version
    - apt-get update && apt-get -y install rsync
  script:
    - kitchen verify $CI_BUILD_NAME
  after_script:
    - kitchen destroy $CI_BUILD_NAME
