---
image: "chef/chefdk:3.1.0"

before_script:
  - export HOME=/opt/chef-secrets/inspec
  - env
  - chef --version

stages:
  - verify
  - publish

inspec_check:
  stage: verify
  script:
    - inspec check .

publish:
  stage: publish
  only:
    - master
  script:
    - inspec compliance upload . --overwrite
